apiVersion: apps/v1
kind: Deployment
metadata:
  name: taylorw8-deployment
spec:
  replicas: 1  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cithit/taylorw8-test1:latest
        ports:
        - containerPort: 81  # Expose NGINX on port 81

---
apiVersion: v1
kind: Service
metadata:
  name: taylorw8-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
      nodePort: 30159
  type: NodePort
